- name: Add Prometheus Helm repo
  shell: helm repo add prometheus-community https://prometheus-community.github.io/helm-charts

- name: Update Helm repos
  shell: helm repo update

- name: Create monitoring namespace
  shell: kubectl create namespace monitoring --dry-run=client -o yaml | kubectl apply -f -

- name: Install Prometheus & Grafana stack
  shell: >
    helm upgrade --install prometheus-stack prometheus-community/kube-prometheus-stack
    --namespace monitoring \
    --set grafana.service.type=NodePort \
    --set grafana.service.nodePort=30001 \
    --set prometheus.service.type=NodePort \
    --set prometheus.service.nodePort=30002
