apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: node-app
  namespace: argocd
  annotations:
    image-version: "{{ .Values.image.tag }}"
spec:
  project: default
  source:
    repoURL: https://github.com/firasboudhraa/CloudDevOpsProject.git
    targetRevision: main
    path: ArgoCd
  destination:
    server: https://kubernetes.default.svc
    namespace: default
  syncPolicy:
    automated:
      prune: true
      selfHeal: true